version: '3'
services:

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wwwroot/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot/ssl:/etc/nginx/ssl
    depends_on:
      - backend

  backend:
    build:
      context: ./server/gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - backend

  auth-service:
    build:
      context: ./server/auth-service
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mysqlDB
      - rabbitmq
    networks:
      - backend

  chat-service:
    build:
      context: ./server/socket-chat
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - redis
      - mysqlDB
      - rabbitmq
    networks:
      - backend

  peer-service:
    build:
      context: ./server/peer-chat
      dockerfile: Dockerfile
    volumes:
      - ./wwwroot/ssl:/usr/src/app/ssl
    ports:
      - "82:81"
      - "9000:9000"
      
    depends_on:
      - redis
      - mysqlDB
      - rabbitmq
    networks:
      - backend

  file_cloud-service:
    build:
      context: ./server/file-cloud
      dockerfile: Dockerfile
    depends_on:
      - mysqlDB
      - rabbitmq
    networks:
      - backend

  mysqlDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - docker.env
    ports:
      - 3309:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysqlDB:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOST=mysqlDB
      - PMA_ARBITRARY=1
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - docker.env
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - backend

volumes:
  mysqlDB:

networks:
  backend:
    driver: bridge