version: '3'
services:

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wwwroot/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqlDB
    networks:
      - backend

  mysqlDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysqlDB:/var/lib/mysql
    networks:
      - backend

volumes:
  mysqlDB:


networks:
  backend:
    driver: bridge
