version: '3'
services:

  mysqlDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3309:3306
    volumes:
      - grafDB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  grafDB:
